### ISSUE TITLE
Adding sft data in pre-training

### ISSUE THREAD

**Issue by jordane95** [OpenBMB/MiniCPM#160]
Hi,

You claimed that adding high-quality sft data in the decay stage of pre-training is beneficial. However, another option is to add these data from scratch, i.e., in the begining of the pre-training stage. I find no experiments regarding this in your report. Have you conducted experiments like this? Since this is the true ablation of the adding high-quality data in the decay stage.

**Comment by LDLINGLINGLING** [comment]
Compared to adding high-quality data at the beginning of the pretraining phase, it better supports training with small data. Otherwise, in an ongoing pretraining process without a pre-determined number of training steps, small data would be repeated too many times, causing negative effects.
The above reasons for not doing this are explained in our blog.
