### ISSUE TITLE
[Bad Case]: DPO FP32 Model - Repeat output

### ISSUE THREAD

**Issue by soulteary** [OpenBMB/MiniCPM#17]
### Description / 描述

参考图片

### Case Explaination / 案例解释

![image](https://github.com/OpenBMB/MiniCPM/assets/1500781/c4bb6d9c-e9a9-417c-a509-bf587e7700e3)

**Comment by ShengdingHu** [comment]
收到，这个情况我们自己也发现啦，应该是精度误差以及huggingface attention的实现导致的，目前解决方案是可以开repetition penalty，稍后我们会更新解决方案。
Understood, we have also noticed this issue. It appears to be caused by precision errors and the implementation of huggingface attention. The current solution is to enable repetition penalty, and we will update with a solution later on.

**Comment by watermeko** [comment]
我在手机上运行也出现了类似的情况，模型一直不停输出相同内容。手机型号是redmi note12turbo，miui14。 
![d3ee43ea9aa3697edeb55011583b6990_720](https://github.com/OpenBMB/MiniCPM/assets/61347352/9d6d643d-a332-4490-9516-4a75062d5604)
