### ISSUE TITLE
[Bad Case]: IOS 应用 找不到CPM设置模板

### ISSUE THREAD

**Issue by qingfengfenga** [OpenBMB/MiniCPM#45]
### Description / 描述

https://github.com/OpenBMB/LLMFarm-MiniCPM

这个文档里选择完模型之后，第二步，IOS App LLM Farm 上找不到这个模板，导致模型无法使用
![image](https://github.com/OpenBMB/MiniCPM/assets/41416092/64e98d0b-0ea5-4588-b479-a9947d7c1709)

**Comment by zkh2016** [comment]
请问你是直接编译安装[LLMFarm-MiniCPM](https://github.com/OpenBMB/LLMFarm-MiniCPM) 的吗?

**Comment by amiglistimo** [comment]
> 请问你是直接编译安装[LLMFarm-MiniCPM](https://github.com/OpenBMB/LLMFarm-MiniCPM) 的吗?

App Store下载的LLMFarm是没有CPM选项的，是需要自己直接编译安装LLMFarm-MiniCPM吗

**Comment by zkh2016** [comment]
issue先关闭了，编译安装LLMFarm-MiniCPM要是有问题可以再讨论。

**Comment by andyweiqiu** [comment]
我现在每次输入后，点击发送就闪退，也不知道什么问题，请问编译安装LLMFarm-MiniCPM还需要注意什么东西啊
中间有个错误：
Error Domain=NSCocoaErrorDomain Code=260 "The file “minicpm-q4_1_1711366402.json.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/qiuwei/Library/Containers/com.qiuwei.LLMFarm/Data/Documents/history/minicpm-q4_1_1711366402.json.json, NSUnderlyingError=0x600001cda7f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
我将chats下面的‘minicpm-q4_1_1711366402.json’拷贝到history下，但是只要输入hello，点击发送就闪退
